### ISSUE TITLE
create a slack bot that greets new users

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP-BLT/BLT-Lettuce#1]

**Comment by JisanAR03** [comment]
> Sure, here's a welcome message for the OWASP Slack community:
> 
> 🎉 **Welcome to the OWASP Slack Community!** 🎉
> 
> We're thrilled to have you here! Whether you're new to OWASP or a long-time contributor, this Slack workspace is the perfect place to connect, collaborate, and stay informed about all things OWASP.
> 
> 🔹 **Get Involved**:
> 
> * Check out the **#contribute** channel to find ways to get involved with OWASP projects and initiatives.
> * Explore individual project channels, which are named **#project-name**, to dive into specific projects that interest you.
> * Join our chapter channels, named **#chapter-name**, to connect with local OWASP members in your area.
> 
> 🔹 **Stay Updated**:
> 
> * Visit **#newsroom** for the latest updates and announcements.
> * Follow **#external-activities** for news about OWASP's engagement with the wider security community.
> 
> 🔹 **Connect and Learn**:
> 
> * **#jobs**: Looking for new opportunities? Check out the latest job postings here.
> * **#leaders**: Connect with OWASP leaders and stay informed about leadership activities.
> * **#project-committee**: Engage with the committee overseeing OWASP projects.
> * **#gsoc**: Stay updated on Google Summer of Code initiatives.
> * **#github-admins**: Get support and discuss issues related to OWASP's GitHub repositories.
> * **#learning**: Share and find resources to expand your knowledge in the field of application security.
> 
> We're excited to see the amazing contributions you'll make. If you have any questions or need assistance, don't hesitate to ask. Let's work together to make software security visible and improve the security of the software we all rely on.
> 
> Welcome aboard! 🚀
> 
> Feel free to customize this message as needed to better fit your community's tone and additional details.

@DonnieBLT sir , i have implement this one ,  when a user join in channel I show this one to the user for now , do you have any other requerment behalf of this welcome message ?

![image](https://github.com/OWASP-BLT/BLT-Lettuce/assets/97744811/40fc2051-7eca-4cda-8b37-1e8cd3c8b420)
